### ISSUE TITLE
Reduce memory of step 05

### ISSUE THREAD

**Issue by simonrasmu** [RasmussenLab/MOVE#16]
Reduce memory of step 05 by changing from dicts to another data structure. Seems to be in the function train_model_association when it saves reconstruction results:

```
---> Works:    with open(path + "results/results_" + version + ".npy", 'wb') as f:
        np.save(f, results)
---> File is truncated   with open(path + "results/results_recon_" + version + ".npy", 'wb') as f:
        np.save(f, recon_results)
    with open(path + "results/results_groups_" + version + ".npy", 'wb') as f:
        np.save(f, groups)
    with open(path + "results/results_recon_mean_baseline_" + version + ".npy", 'wb') as f:
        np.save(f, mean_bas)
    with open(path + "results/results_recon_no_corr_" + version + ".npy", 'wb') as f:
        np.save(f, recon_results_1)
```

Ie when it tries to save the recon_results as results/results_recon_v1.npy
When i try to load it I get EOFError:

```
recon_results = np.load(processed_data_path + "results/results_recon_" + version + ".npy", allow_pickle=True).item()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kjv627/miniforge3/envs/move/lib/python3.9/site-packages/numpy/lib/npyio.py", line 430, in load
    return format.read_array(fid, allow_pickle=allow_pickle,
  File "/Users/kjv627/miniforge3/envs/move/lib/python3.9/site-packages/numpy/lib/format.py", line 747, in read_array
    array = pickle.load(fp, **pickle_kwargs)
EOFError: Ran out of input
```

So it seems it wasnt written correctly

**Comment by enryH** [comment]
@valentas1 if you created a commit to fix it, it might be worth to just paste it here (then it is documented, whenever this error might occur again?)

**Comment by valentas1** [comment]
Okay. I will add the commits to all issue threads from now on.

**Comment by valentas1** [comment]
89b93a55994cfd3b9611449762911ed2d2988157
